version: '3'

services:
    app:
        build: ./stack
        depends_on:
            - postgres
        command: npm start
        ports:
            - "5000:5000"
        volumes:
            - ./:/stats:delegated
        environment:
            DATABASE_URL: postgres://stats@postgres/stats
    postgres:
        image: postgres:11.2-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: stats
            POSTGRES_DB: stats
