version: '3'

volumes:
    db-data:

services:
    app:
        build: ./stack
        depends_on:
            - db
        command: npm start
        ports:
            - "5000:5000"
        volumes:
            - ./:/stats:delegated
        environment:
            DATABASE_URL: postgresql://postgres@db:5432/stats
    db:
        image: postgres:12.2-alpine
        ports:
            - "5438:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
            - /tmp:/tmp
        environment:
            POSTGRES_DB: stats
            POSTGRES_HOST_AUTH_METHOD: trust
